package com.yychat.model;

public interface MessageType {
    String LOGIN_VALLDATE_SUCCESS = "1";
    String LOGIN_VALLDATE_FALLURE = "2";
    String COMMON_CHAT_MESSAGE = "3";
    String REQUEST_ONLINE_FRIEND="4";
    String RESPONSE_ONLINE_FRIEND="5";
    String NEW_ONLINE_TO_ALL_FRIEND="6";
    String NEW_ONLINE_FRIEND="7";
    String USER_REGISTER_SUCCESS = "8";
    String USER_REGISTER_FAILURE="9";
    String ADD_NEW_FRIEND = "10";
    String ADD_NEW_FRIEND_FALLURE_NO_USER="11";
    String ADD_NEW_FRIEND_FALLURE_ALREADY_FRIEND="12";
    String ADD_NEW_FRIEND_SUCCESS="13";
    String USER_EXIT_SERVER_THREAD_CLOSE = "14";
    String USER_EXIT_CLIENT_THREAD_CLOSE = "15";
}
